import assert from "node:assert/strict";
import test from "node:test";

import { FakeGame } from "./fakeGame.ts";
import { DEFAULT_VIEW_SIZE, MAX_VIEW_SIDE, MIN_VIEW_SIZE, renderMapView } from "../src/park/mapView.ts";
import type { MapViewOutcome, MapViewSuccess } from "../src/park/mapView.ts";
import { MapViewTools } from "../src/tools/mapView.ts";
import { getMcpTools } from "../src/tools/index.ts";
import { getMcpToolDefinitions } from "../src/tools/decorators.ts";

/**
 * This used to be a grid and the grid is what failed. It drew one character per tile under a
 * two-row vertical-digit header, and on session 01a09887 the model got 14 of 27 tile claims
 * right, every error the same one-column shift, after spending a third of its output budget
 * on column arithmetic and then refusing to call the tool again.
 *
 * So the property these tests exist to hold is no longer "the header and the body agree". It
 * is that A TILE AT A NAMED COORDINATE IS RECOVERABLE FROM THE OUTPUT WITHOUT COUNTING
 * ANYTHING, and `parseRows` below is the whole of it: it turns the rows back into tiles by
 * reading numbers, refuses a row whose runs are not contiguous from `area.fromX` to
 * `area.toX`, and the fixtures then compare every tile of the window against a map the test
 * planted rather than against anything the renderer computed. A run boundary that moves by
 * one, a run dropped, a kind that changes, a row that loses its y - each of those fails on
 * the tile it touches and names it.
 *
 * The fixtures plant ground tile by tile and hold their own expectation, so the check is
 * against the park the test built and not against a second copy of the renderer's precedence
 * rules. A table regenerated by the same reasoning that produced a bug agrees with the bug.
 */

function withGame(build: (game: FakeGame) => void, run: (game: FakeGame) => void, size = 40): void {
    const game = new FakeGame(size, size);
    build(game);
    const restore = game.install();

    try {
        run(game);
    } finally {
        restore();
    }
}

function drawn(outcome: MapViewOutcome): MapViewSuccess {
    assert.equal(outcome.ok, true, outcome.ok ? "" : outcome.error);
    return outcome as MapViewSuccess;
}

/** `<firstX>-<lastX><kind>`, both ends always, kind never starting with a digit. */
const RUN = /^(\d+)-(\d+)([^\s\d][^\s]*)$/;

/**
 * Every tile of the window, keyed "x,y", read back out of the rows.
 *
 * Nothing here counts a position: a tile's x comes from the numbers written beside it, and a
 * row's y from the label the row carries. The contiguity assertions are the other half - a
 * format that lets a tile fall between two runs, or into two of them, would let the renderer
 * lose a tile silently, which is the failure the grid's header was there to prevent.
 */
function parseRows(view: MapViewSuccess): Record<string, string> {
    const tiles: Record<string, string> = {};
    const rows = view.rows.filter(function (row) { return row.indexOf("cut:") !== 0; });

    assert.equal(rows.length, view.area.toY - view.area.fromY + 1,
        "one line per y of `area` and no others");

    for (let i = 0; i < rows.length; i++) {
        const head = /^y(\d+): /.exec(rows[i]);

        assert.ok(head, "a row has to name its own y: " + JSON.stringify(rows[i]));

        const y = Number((head as RegExpExecArray)[1]);

        assert.equal(y, view.area.fromY + i,
            "rows run in ascending y from area.fromY: " + JSON.stringify(rows[i]));

        const parts = rows[i].substring((head as RegExpExecArray)[0].length).split(" ");
        let next = view.area.fromX;

        for (let p = 0; p < parts.length; p++) {
            const run = RUN.exec(parts[p]);

            assert.ok(run, "a run has to read `<firstX>-<lastX><kind>`: "
                + JSON.stringify(parts[p]) + " in " + JSON.stringify(rows[i]));

            const from = Number((run as RegExpExecArray)[1]);
            const to = Number((run as RegExpExecArray)[2]);
            const kind = (run as RegExpExecArray)[3];

            assert.ok(to >= from, "a run cannot end before it starts: " + parts[p]);
            assert.equal(from, next, "run " + parts[p] + " on " + JSON.stringify(rows[i])
                + " starts at " + String(from) + " and the run before it ended at "
                + String(next - 1) + "; a gap or an overlap here is a tile the reader cannot place");

            for (let x = from; x <= to; x++) {
                tiles[String(x) + "," + String(y)] = kind;
            }

            next = to + 1;
        }

        assert.equal(next, view.area.toX + 1, "the last run of " + JSON.stringify(rows[i])
            + " ends at " + String(next - 1) + " and area.toX is " + String(view.area.toX));
    }

    return tiles;
}

/** The kind the rows give for one tile, with no counting and no formula. */
function kindAt(view: MapViewSuccess, x: number, y: number): string {
    const tiles = parseRows(view);
    const key = String(x) + "," + String(y);

    assert.ok(Object.prototype.hasOwnProperty.call(tiles, key),
        "the rows do not cover " + key + " at all");

    return tiles[key];
}

function countOf(view: MapViewSuccess, kind: string): number {
    const tiles = parseRows(view);
    let found = 0;

    for (const key in tiles) {
        if (tiles[key] === kind) {
            found++;
        }
    }

    return found;
}

/** A ride the fake will report, without going through ridecreate. */
function addRide(game: FakeGame, id: number): void {
    game.rides.push({
        id: id, name: "Ride " + String(id), type: 0, status: "closed", price: [0],
        stations: [{ start: null, entrance: null, exit: null, length: 0, queueTime: 0 }],
        excitement: -1, intensity: 0, nausea: 0, totalCustomers: 0, totalProfit: 0,
        downtime: 0, reliability: 100, flags: 0, value: null
    });
}

function addTrack(game: FakeGame, x: number, y: number, ride: number): void {
    game.tile(x, y).elements.push({ type: "track", baseZ: 96, ride: ride, trackType: 0, direction: 0 });
}

function addWater(game: FakeGame, x: number, y: number): void {
    Object.assign(game.tile(x, y).elements[0], { waterHeight: 112 });
}

// ---------------------------------------------------------------------------
// The property the grid lost: every tile of the window, recovered by name.
// ---------------------------------------------------------------------------

/**
 * A park with one tile of every kind the renderer can produce, planted at coordinates the
 * test chose, plus the expectation for every one of the 900 tiles in the window.
 *
 * The expectation is built from the plan, not from the park: `EXPECTED` is written out by
 * hand and the fixture's job is to make the game match it. So a renderer that agreed with a
 * wrong precedence rule still fails, and so does one that draws the right shape one column
 * over.
 */
const OWNED = { fromX: 10, fromY: 10, toX: 29, toY: 29 };

const PLANTED: Record<string, string> = {
    "20,12": "G", "21,12": "G", "22,12": "G",
    "12,14": "r0", "13,14": "r0",
    "15,14": "r26",
    "17,14": "r137",
    "12,16": "N",
    "14,16": "X",
    "16,16": "P",
    "18,16": "Q",
    "24,16": "UP",
    "26,16": "UQ",
    "12,18": "S",
    "14,18": "^",
    "16,18": "~",
    "18,18": "!",
    "20,18": "?",
    "22,18": "U",
    "12,22": "P", "13,22": "P", "14,22": "P", "15,22": "P", "16,22": "P",
    "17,22": "P", "18,22": "P", "19,22": "P", "20,22": "P"
};

function plantedPark(game: FakeGame): void {
    for (let x = 0; x < 40; x++) {
        for (let y = 0; y < 40; y++) {
            game.own(x, y, x >= OWNED.fromX && x <= OWNED.toX && y >= OWNED.fromY && y <= OWNED.toY);
        }
    }

    addRide(game, 0);
    addRide(game, 26);
    addRide(game, 137);

    game.addParkEntrance(20, 12);
    addTrack(game, 12, 14, 0);
    addTrack(game, 13, 14, 0);
    addTrack(game, 15, 14, 26);
    addTrack(game, 17, 14, 137);
    game.addRideEntrance(12, 16, 0, 0);
    game.addRideEntrance(14, 16, 0, 0, true);
    game.addPath(16, 16);
    game.addPath(18, 16, true);

    game.own(24, 16, false);
    game.addPath(24, 16);
    game.own(26, 16, false);
    game.addPath(26, 16, true);

    game.addScenery(12, 18);
    game.tile(14, 18).elements[0].slope = 4;
    addWater(game, 16, 18);
    game.tile(18, 18).elements.push({ type: "something_new", baseZ: 96 });
    game.tile(20, 18).elements = [];
    game.own(22, 18, false);

    for (let x = 12; x <= 20; x++) {
        game.addPath(x, 22);
    }
}

/** What the window should hold, from the plan: unowned outside, empty inside, plants on top. */
function expectedOf(fromX: number, fromY: number, toX: number, toY: number): Record<string, string> {
    const expected: Record<string, string> = {};

    for (let y = fromY; y <= toY; y++) {
        for (let x = fromX; x <= toX; x++) {
            const key = String(x) + "," + String(y);
            const inside = x >= OWNED.fromX && x <= OWNED.toX && y >= OWNED.fromY && y <= OWNED.toY;

            expected[key] = Object.prototype.hasOwnProperty.call(PLANTED, key)
                ? PLANTED[key]
                : (inside ? "E" : "U");
        }
    }

    return expected;
}

test("every tile of the window is recoverable from the rows by name", function () {
    withGame(plantedPark, function () {
        const view = drawn(renderMapView({ left: 5, top: 5, right: 34, bottom: 34 }));
        const tiles = parseRows(view);
        const expected = expectedOf(5, 5, 34, 34);
        const wrong: string[] = [];

        for (const key in expected) {
            if (tiles[key] !== expected[key]) {
                wrong.push(key + " is " + JSON.stringify(tiles[key]) + " and the park has "
                    + JSON.stringify(expected[key]));
            }
        }

        assert.deepEqual(wrong, [], "the rows disagree with the planted park on "
            + String(wrong.length) + " of 900 tiles");
        assert.equal(Object.keys(tiles).length, 900,
            "900 tiles are in the window and every one of them has to be in exactly one run");
    });
});

test("the same tiles come back at the same coordinates through a window that starts elsewhere", function () {
    // The grid's error was a constant offset, which a single window cannot catch: the picture
    // was self-consistent and one column out. Two windows with different origins over the same
    // ground have to agree tile for tile, and an offset that depends on the window does not.
    withGame(plantedPark, function () {
        const wide = parseRows(drawn(renderMapView({ left: 5, top: 5, right: 34, bottom: 34 })));
        const narrow = parseRows(drawn(renderMapView({ left: 11, top: 13, right: 27, bottom: 23 })));
        const disagree: string[] = [];

        for (const key in narrow) {
            if (wide[key] !== narrow[key]) {
                disagree.push(key + ": " + JSON.stringify(wide[key]) + " vs " + JSON.stringify(narrow[key]));
            }
        }

        assert.deepEqual(disagree, [], "two windows over the same ground disagree");
        assert.equal(Object.keys(narrow).length, 17 * 11);
    });
});

test("a coordinate past 99 is written out, not widened, truncated or split", function () {
    // The grid needed a third header row here and the digits of one x ran down three lines.
    // A number is a number at any size, which is the whole of what replaced that.
    withGame(function (game) {
        game.addScenery(104, 101);
        game.own(100, 101, false);
    }, function () {
        const view = drawn(renderMapView({ left: 96, top: 95, right: 115, bottom: 110 }));

        assert.equal(kindAt(view, 104, 101), "S");
        assert.equal(kindAt(view, 100, 101), "U");
        assert.equal(kindAt(view, 99, 101), "E", "the columns either side of the hundreds roll are still themselves");
        assert.equal(kindAt(view, 101, 101), "E");
        assert.ok(view.rows[0].indexOf("y95: 96-") === 0,
            "a row of three-digit ground still names its y and starts at area.fromX: " + view.rows[0]);
    }, 128);
});

test("a run of one tile writes both its ends", function () {
    // `51P` has a reading in English - fifty-one path tiles - and leaves the reader to work
    // out where the run ended before the next one can be chained onto it. Both are the kind
    // of implicit step the grid died of, so a single tile costs three more characters.
    withGame(plantedPark, function () {
        const view = drawn(renderMapView({ left: 10, top: 16, right: 20, bottom: 16 }));

        assert.equal(view.rows.length, 1);
        assert.equal(view.rows[0], "y16: 10-11E 12-12N 13-13E 14-14X 15-15E 16-16P 17-17E 18-18Q 19-20E",
            "every run names both ends, a one-tile run included");
    });
});

// ---------------------------------------------------------------------------
// The kinds: one kind for one thing, and the same thing for that kind.
// ---------------------------------------------------------------------------

test("each kind is written for the thing it means and for nothing else", function () {
    withGame(plantedPark, function () {
        const view = drawn(renderMapView({ left: 5, top: 5, right: 34, bottom: 34 }));

        assert.equal(countOf(view, "G"), 3, "the gate is three tiles and nothing else is a gate");
        assert.equal(countOf(view, "N"), 1);
        assert.equal(countOf(view, "X"), 1);
        assert.equal(countOf(view, "r0"), 2);
        assert.equal(countOf(view, "r26"), 1);
        assert.equal(countOf(view, "r137"), 1);
        assert.equal(countOf(view, "Q"), 1, "the unowned queue must not also count as the park's");
        assert.equal(countOf(view, "UQ"), 1);
        assert.equal(countOf(view, "P"), 10, "one path tile and the nine-tile walk, and no queue among them");
        assert.equal(countOf(view, "UP"), 1);
        assert.equal(countOf(view, "S"), 1);
        assert.equal(countOf(view, "^"), 1);
        assert.equal(countOf(view, "~"), 1);
        assert.equal(countOf(view, "!"), 1);
        assert.equal(countOf(view, "?"), 1);
    });
});

test("a queue and a footpath on the same tile are different kinds", function () {
    withGame(function (game) {
        game.addPath(9, 9, true);
    }, function (game) {
        const asQueue = drawn(renderMapView({ left: 5, top: 5, right: 14, bottom: 14 }));
        assert.equal(kindAt(asQueue, 9, 9), "Q");

        game.tile(9, 9).elements = game.tile(9, 9).elements.filter(function (element) {
            return element.type !== "footpath";
        });
        game.addPath(9, 9);

        const asPath = drawn(renderMapView({ left: 5, top: 5, right: 14, bottom: 14 }));
        assert.equal(kindAt(asPath, 9, 9), "P",
            "the same tile with an ordinary path on it has to read differently from a queue");
    });
});

test("no kind is a prefix of a coordinate, so a run cannot be read two ways", function () {
    // The kinds and the spans share one line, so a kind beginning with a digit or carrying a
    // hyphen would make `12-14r3` ambiguous. This is generated from what actually rendered.
    withGame(plantedPark, function () {
        const view = drawn(renderMapView({ left: 5, top: 5, right: 34, bottom: 34 }));
        const tiles = parseRows(view);
        const seen: Record<string, boolean> = {};

        for (const key in tiles) {
            seen[tiles[key]] = true;
        }

        const kinds = Object.keys(seen);

        assert.ok(kinds.length >= 14, "this window is supposed to hold nearly every kind, and holds "
            + String(kinds.length));

        for (let i = 0; i < kinds.length; i++) {
            assert.doesNotMatch(kinds[i], /^\d/, "a kind starting with a digit runs into the span: " + kinds[i]);
            assert.doesNotMatch(kinds[i], /[-\s]/, "a kind carrying a hyphen or a space splits the run: " + kinds[i]);
        }
    });
});

// ---------------------------------------------------------------------------
// Precedence. One kind a tile means collapsing, and the tool description states the order,
// so the renderer has to follow exactly that order.
// ---------------------------------------------------------------------------

test("ground that can never be built on outranks scenery standing on it", function () {
    withGame(function (game) {
        game.tile(10, 10).elements[0].slope = 4;
        game.addScenery(10, 10);
        game.addScenery(11, 10);
        game.own(12, 10, false);
        game.addScenery(12, 10);
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 14 }));

        assert.equal(kindAt(view, 10, 10), "^",
            "clearing a tree off sloped ground does not make it buildable, so the slope is the fact");
        assert.equal(kindAt(view, 11, 10), "S", "on flat park land the tree is the fact: clearing it works");
        assert.equal(kindAt(view, 12, 10), "U");
    });
});

test("water outranks ownership and ownership outranks slope", function () {
    withGame(function (game) {
        addWater(game, 10, 10);
        game.own(10, 10, false);
        game.own(11, 10, false);
        game.tile(11, 10).elements[0].slope = 4;
        game.tile(12, 10).elements[0].slope = 4;
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 14 }));

        assert.equal(kindAt(view, 10, 10), "~", "unowned water is still water");
        assert.equal(kindAt(view, 11, 10), "U", "unowned sloped land reads as not the park's");
        assert.equal(kindAt(view, 12, 10), "^");
    });
});

test("anything built outranks the ground it stands on", function () {
    withGame(function (game) {
        addRide(game, 0);
        game.addPath(10, 10);
        game.addRideEntrance(10, 10, 0, 0);
        game.tile(11, 10).elements[0].slope = 4;
        game.addPath(11, 10);
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 14 }));

        assert.equal(kindAt(view, 10, 10), "N",
            "the building is the salient thing; a P here would hide a ride door");
        assert.equal(kindAt(view, 11, 10), "P", "a path on sloped ground is still a path");
    });
});

// ---------------------------------------------------------------------------
// Ride track names its ride, which is what the lettering and the `rides` table were for.
// ---------------------------------------------------------------------------

test("track carries the ride's own id, at any id, with nothing to look it up in", function () {
    withGame(function (game) {
        addRide(game, 0);
        addRide(game, 2);
        addRide(game, 26);
        addRide(game, 137);
        addTrack(game, 10, 10, 0);
        addTrack(game, 11, 10, 0);
        addTrack(game, 13, 10, 2);
        addTrack(game, 15, 10, 26);
        addTrack(game, 17, 10, 137);
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 20, bottom: 14 }));

        assert.equal(view.rows[2], "y10: 8-9E 10-11r0 12-12E 13-13r2 14-14E 15-15r26 16-16E 17-17r137 18-20E",
            "two touching tiles of one ride are one run, and each ride is its own id");
        assert.equal(kindAt(view, 13, 10), "r2",
            "ride 2 is r2; the grid drew it `c`, the third letter, which is a different number");
        assert.equal(kindAt(view, 15, 10), "r26",
            "ride 26 had no letter at all and the grid drew it `#`, which two overflowing rides shared");
        assert.equal(kindAt(view, 17, 10), "r137");
        assert.equal(typeof (view as unknown as Record<string, unknown>).rides, "undefined",
            "the id is in the picture, so there is nothing left to map letters back with");
    });
});

// ---------------------------------------------------------------------------
// Honesty: nothing inferred, nothing filled in.
// ---------------------------------------------------------------------------

test("an empty park reads as empty and invents nothing", function () {
    withGame(function () { /* nothing at all */ }, function () {
        const view = drawn(renderMapView({ left: 4, top: 4, right: 12, bottom: 12 }));

        assert.deepEqual(view.rows, [
            "y4: 4-12E", "y5: 4-12E", "y6: 4-12E", "y7: 4-12E", "y8: 4-12E",
            "y9: 4-12E", "y10: 4-12E", "y11: 4-12E", "y12: 4-12E"
        ], "untouched park is one run of flat owned ground a row, and nine rows of it");
        assert.equal(view.clipped, false);
    });
});

test("a tile with no surface element reads as unknown rather than as ground", function () {
    withGame(function (game) {
        game.tile(10, 10).elements = [];
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 14 }));

        assert.equal(kindAt(view, 10, 10), "?");
    });
});

test("an element this map cannot name is shown, not quietly dropped", function () {
    withGame(function (game) {
        game.tile(10, 10).elements.push({ type: "something_new", baseZ: 96 });
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 14 }));

        assert.equal(kindAt(view, 10, 10), "!",
            "a blocker with no kind of its own must not read as empty buildable ground");
    });
});

// ---------------------------------------------------------------------------
// The window: clipping, refusals, and what the result says about both.
// ---------------------------------------------------------------------------

test("a window over the map edge is cut down and says so in the rows", function () {
    withGame(function (game) {
        game.addScenery(38, 38);
    }, function () {
        const view = drawn(renderMapView({ left: 30, top: 30, right: 50, bottom: 45 }));
        const cut = view.rows.filter(function (row) { return row.indexOf("cut:") === 0; });

        assert.equal(view.clipped, true);
        assert.deepEqual(view.area, { fromX: 30, fromY: 30, toX: 39, toY: 39 });
        assert.equal(cut.length, 1,
            "a smaller window handed back in silence reads as `there is nothing out there`, and"
            + " the field that used to carry this sat outside the text that gets read");
        assert.ok(cut[0].indexOf("0-39 in x") >= 0 && cut[0].indexOf("0-39 in y") >= 0,
            "the line has to name where the map actually ends: " + cut[0]);
        assert.ok(cut[0].indexOf("x 30-39, y 30-39") >= 0,
            "and what was read instead: " + cut[0]);
        assert.equal(kindAt(view, 38, 38), "S");
        assert.equal(view.rows[view.rows.length - 1], cut[0], "the line comes after the ground, not among it");
    });
});

test("a window inside the map carries no cut line at all", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(renderMapView({ left: 10, top: 10, right: 20, bottom: 20 }));

        assert.equal(view.clipped, false);
        assert.equal(view.rows.filter(function (row) { return row.indexOf("cut:") === 0; }).length, 0,
            "a line saying the window was cut, on a window that was not, is the same lie the other way");
    });
});

test("a window entirely off the map is refused rather than drawn empty", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = renderMapView({ left: 60, top: 60, right: 70, bottom: 70 });

        assert.equal(outcome.ok, false);
        assert.ok(outcome.ok === false && outcome.error.indexOf("off the map") >= 0);
    });
});

test("a window larger than the cap is refused with its own measurements", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = renderMapView({ left: 0, top: 0, right: MAX_VIEW_SIDE, bottom: 5 });

        assert.equal(outcome.ok, false);
        assert.ok(outcome.ok === false && outcome.error.indexOf(String(MAX_VIEW_SIDE + 1) + " by 6") >= 0,
            "the refusal has to name the size that was asked for: " + (outcome.ok === false ? outcome.error : ""));
    }, 64);
});

test("a window of exactly the cap is drawn", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(renderMapView({ left: 0, top: 0, right: MAX_VIEW_SIDE - 1, bottom: MAX_VIEW_SIDE - 1 }));

        assert.equal(view.rows.length, MAX_VIEW_SIDE);
        assert.equal(Object.keys(parseRows(view)).length, MAX_VIEW_SIDE * MAX_VIEW_SIDE);
    });
});

// ---------------------------------------------------------------------------
// The tool layer: which form a call means, and what a half-written one is told.
// ---------------------------------------------------------------------------

interface ToolFailure {
    ok: false;
    error: string;
}

function callTool(args: Record<string, unknown>): MapViewOutcome | ToolFailure {
    return new MapViewTools().viewMap(args) as MapViewOutcome | ToolFailure;
}

test("view_map is registered, and declares the bounds mcp.ts enforces", function () {
    const definitions = getMcpToolDefinitions(MapViewTools);

    assert.equal(definitions.length, 1);
    assert.equal(definitions[0].name, "view_map");
    assert.equal(definitions[0].inputSchema.additionalProperties, false);
    assert.equal(typeof definitions[0].inputSchema.required, "undefined",
        "a call with no arguments at all is the commonest one and has to be legal");

    const properties = definitions[0].inputSchema.properties as Record<string, Record<string, unknown>>;
    assert.deepEqual(Object.keys(properties).sort(),
        ["fromX", "fromY", "margin", "size", "toX", "toY", "x", "y"]);
    assert.equal(properties.size.maximum, MAX_VIEW_SIDE);
    assert.equal(properties.size.minimum, MIN_VIEW_SIZE);
    assert.equal(properties.margin.minimum, 0);
    assert.equal(typeof properties.margin.maximum, "number");
    assert.equal(properties.x.minimum, 0);
    assert.equal(properties.fromX.minimum, 0);

    const registered = getMcpTools().filter(function (tool) { return tool.name === "view_map"; });
    assert.equal(registered.length, 1, "the tool has to be in the registry or the model never sees it");
    assert.equal(registered[0].annotations?.readOnlyHint, true, "this tool changes nothing");
});

/**
 * The legend used to explain every character the render had used, and was read 0 times across
 * the measured run. It is gone, so the kinds are explained in the one piece of text that is
 * in context on every turn the tool is in play - and this is generated from what actually
 * rendered, so a kind the renderer can produce and the description never mentions fails here.
 */
test("the tool description names every kind the renderer can produce", function () {
    const description = String(getMcpTools().filter(function (tool) {
        return tool.name === "view_map";
    })[0].description);

    withGame(plantedPark, function () {
        const tiles = parseRows(drawn(renderMapView({ left: 5, top: 5, right: 34, bottom: 34 })));
        const seen: Record<string, boolean> = {};

        for (const key in tiles) {
            // Every ride is its own kind, and what the description has to carry is the rule.
            seen[/^r\d+$/.test(tiles[key]) ? "r" : tiles[key]] = true;
        }

        const kinds = Object.keys(seen).sort();

        assert.deepEqual(kinds, ["!", "?", "E", "G", "N", "P", "Q", "S", "U", "UP", "UQ", "X", "^", "r", "~"],
            "the planted park is supposed to hold one of everything; if it does not, this test"
            + " is only checking the kinds it happens to reach");

        for (let i = 0; i < kinds.length; i++) {
            assert.ok(description.indexOf("`" + kinds[i] + "`") >= 0,
                "the renderer writes " + JSON.stringify(kinds[i]) + " and the description never says what it is");
        }
    });

    assert.ok(description.indexOf("`r3` is the ride `park_status` reports as id 3") >= 0,
        "and what the number after `r` is, which is the whole of the ride kind");
});

test("the description describes the format that shipped, not the grid it replaced", function () {
    const description = String(getMcpTools().filter(function (tool) {
        return tool.name === "view_map";
    })[0].description);

    assert.ok(description.indexOf("<firstX>-<lastX><kind>") >= 0, "the shape of a run");
    assert.ok(description.indexOf("both ends") >= 0, "and that a one-tile run writes both of them");
    assert.ok(description.indexOf("contiguous") >= 0 && description.indexOf("area.toX") >= 0,
        "and the invariant that lets the reader check a row: the runs cover it with no gap");

    // Six places agreeing with each other is not evidence, and a description that still
    // promises a grid is a fact the model reads on every turn and cannot check.
    assert.doesNotMatch(description, /ONE CHARACTER IS ONE TILE|one digit place per row|text grid/,
        "the grid's own sentences must not survive the grid");
    assert.doesNotMatch(description, /`legend`|`rides`/,
        "neither field exists any more, and naming one sends the model looking for it");
});

test("no arguments at all reads a square around the park's own gate", function () {
    withGame(function (game) {
        game.addParkEntrance(18, 20);   // 18, 19 and 20 at y 20
    }, function () {
        const view = drawn(callTool({}) as MapViewOutcome);

        assert.equal(view.area.fromX <= 19 && 19 <= view.area.toX, true);
        assert.equal(view.area.fromY <= 20 && 20 <= view.area.toY, true);
        assert.equal(view.area.toX - view.area.fromX + 1, DEFAULT_VIEW_SIZE);
        assert.equal(kindAt(view, 19, 20), "G");
    });
});

test("a park with no gate is told which two forms to use instead", function () {
    withGame(function () { /* no entrance anywhere */ }, function () {
        const outcome = callTool({}) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("no gate") >= 0);
        assert.ok(outcome.error.indexOf("fromX") >= 0 && outcome.error.indexOf("`x`") >= 0);
    });
});

test("a site's four bounds are read with room around them", function () {
    withGame(function (game) {
        game.addScenery(20, 20);
    }, function () {
        const view = drawn(callTool({ fromX: 15, fromY: 15, toX: 18, toY: 18, margin: 3 }) as MapViewOutcome);

        assert.deepEqual(view.area, { fromX: 12, fromY: 12, toX: 21, toY: 21 });
        assert.equal(kindAt(view, 20, 20), "S", "the margin is read, not just the site");
    });
});

/**
 * `requested` said "the window asked for" and reported the margin-grown rectangle, which is a
 * window nobody asked for. Same defect as `hire_staff` reporting a clamped `count` as the
 * number requested: a small lie about what the caller said.
 */
test("`requested` is the corners the caller named, and `area` is those plus the margin", function () {
    withGame(function () { /* empty */ }, function () {
        const withMargin = drawn(callTool({ fromX: 15, fromY: 16, toX: 18, toY: 19, margin: 3 }) as MapViewOutcome);

        assert.deepEqual(withMargin.requested, { fromX: 15, fromY: 16, toX: 18, toY: 19 },
            "these four numbers are the ones the call carried, and nothing was added to them");
        assert.deepEqual(withMargin.area, { fromX: 12, fromY: 13, toX: 21, toY: 22 });

        const corners = drawn(callTool({ fromX: 18, fromY: 19, toX: 15, toY: 16, margin: 0 }) as MapViewOutcome);

        assert.deepEqual(corners.requested, { fromX: 15, fromY: 16, toX: 18, toY: 19 },
            "corners given the other way round are the same rectangle, sorted rather than grown");
        assert.deepEqual(corners.area, corners.requested, "and with no margin there is nothing between them");

        const square = drawn(callTool({ x: 20, y: 24, size: 5 }) as MapViewOutcome);

        assert.deepEqual(square.requested, { fromX: 18, fromY: 22, toX: 22, toY: 26 },
            "a square names its own window exactly, so `requested` and `area` are one rectangle");
        assert.deepEqual(square.area, square.requested);
    });
});

test("a window the map's edge cut still reports the corners the caller named", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(callTool({ fromX: 34, fromY: 34, toX: 37, toY: 37, margin: 4 }) as MapViewOutcome);

        assert.equal(view.clipped, true, "38 and 39 exist, 40 and 41 do not");
        assert.deepEqual(view.requested, { fromX: 34, fromY: 34, toX: 37, toY: 37 },
            "clipping cuts the ground read, and changes nothing about what was asked for");
        assert.deepEqual(view.area, { fromX: 30, fromY: 30, toX: 39, toY: 39 });
    });
});

test("the margin has a default, so four copied bounds are enough on their own", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(callTool({ fromX: 15, fromY: 15, toX: 18, toY: 18 }) as MapViewOutcome);

        assert.deepEqual(view.area, { fromX: 11, fromY: 11, toX: 22, toY: 22 });
    });
});

test("a square is centred on x,y exactly as clear_scenery centres one", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(callTool({ x: 20, y: 20, size: 5 }) as MapViewOutcome);

        assert.deepEqual(view.area, { fromX: 18, fromY: 18, toX: 22, toY: 22 });
    });
});

test("mixing the two forms is refused, and the refusal sorts the arguments out", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ x: 10, y: 10, fromX: 4, fromY: 4, toX: 8, toY: 8 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("mixes them") >= 0);
        assert.ok(outcome.error.indexOf("`x`, `y`") >= 0);
        assert.ok(outcome.error.indexOf("`fromX`, `fromY`, `toX`, `toY`") >= 0);
    });
});

test("half a rectangle is refused rather than squared off into different ground", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ fromX: 4, fromY: 4, toX: 8 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("`toY`") >= 0);
    });
});

test("an x with no y is refused, and told about the gate-centred default", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ x: 10 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("only `x`") >= 0);
        assert.ok(outcome.error.indexOf("gate") >= 0);
    });
});

/**
 * THE REFUSAL DESCRIBED SOMEBODY ELSE'S CALL.
 *
 * Session 01a098b4: the model called `view_map {"margin": 5}` and was told "A rectangle needs
 * all four of `fromX`, `fromY`, `toX` and `toY`". `margin` is in RECT_ARGS, so passing it
 * alone selected the rectangle form and then failed it, and the sentence that came back named
 * four arguments the call had not sent and never once said the word `margin`. The model tried
 * again with `margin` 10, got the same sentence, and had spent 2 of its 4 view_map calls
 * before it stopped asking; it then planned ten mutating turns off a map it had never seen.
 *
 * So the property is not "a bad call is refused". It is that A REFUSAL NAMES THE CALL IT IS
 * REFUSING: every argument that was actually passed, and the forms that would have worked.
 * These assert the text, because the text is the whole of what the model gets.
 */

/** Every refusal that leaves the caller with no window has to say what would give it one. */
function assertNamesTheForms(error: string): void {
    assert.ok(error.indexOf("`fromX`, `fromY`, `toX` and `toY` as a rectangle") >= 0,
        "the rectangle form is one of the three and has to be named: " + error);
    assert.ok(error.indexOf("`x`, `y` and `size` as a square") >= 0,
        "so is the square form: " + error);
    assert.ok(error.indexOf("park's own gate") >= 0,
        "and so is the gate-centred default: " + error);
}

test("`margin` on its own is refused by name, not as four corners it never mentioned", function () {
    withGame(function () { /* empty */ }, function () {
        for (const value of [0, 5, 10]) {
            const outcome = callTool({ margin: value }) as ToolFailure;

            assert.equal(outcome.ok, false);
            assert.equal(outcome.error.indexOf("This call passed `margin`."), 0,
                "the refusal opens with the argument the call actually carried: " + outcome.error);
            assert.ok(outcome.error.indexOf("`margin` is the ground read around a rectangle and"
                + " selects no window on its own") >= 0,
                "and says what `margin` is and what it is not: " + outcome.error);
            assert.ok(outcome.error.indexOf("applies only together with `fromX`, `fromY`, `toX`"
                + " and `toY`") >= 0,
                "and what it needs beside it: " + outcome.error);
            assertNamesTheForms(outcome.error);

            // The measured failure, asserted directly: being told four arguments were "left
            // out" of a call that named none of them is an answer to a question nobody asked.
            assert.ok(outcome.error.indexOf("left out") < 0,
                "nothing was left out of a call that named no corners at all: " + outcome.error);
            assert.ok(outcome.error.indexOf("A rectangle needs all four") < 0,
                "and this call did not ask for a rectangle: " + outcome.error);
        }
    });
});

test("`margin` beside the square form is refused as a mixed call, with both names in it", function () {
    withGame(function () { /* empty */ }, function () {
        const centred = callTool({ x: 10, y: 10, size: 5, margin: 3 }) as ToolFailure;

        assert.equal(centred.ok, false);
        assert.equal(centred.error.indexOf("This call passed `x`, `y`, `size`, `margin`."), 0,
            "every argument the call carried, in the refusal: " + centred.error);
        assert.ok(centred.error.indexOf("`margin` to the rectangle form") >= 0, centred.error);
        assert.ok(centred.error.indexOf("`x`, `y`, `size` belong to the square form") >= 0, centred.error);
        assertNamesTheForms(centred.error);

        // `size` alone is the gate-centred default, so `size` plus `margin` is that form and
        // the rectangle form at once - and the refusal has to name `margin`, not just `size`.
        const gateSized = callTool({ size: 7, margin: 3 }) as ToolFailure;

        assert.equal(gateSized.ok, false);
        assert.equal(gateSized.error.indexOf("This call passed `size`, `margin`."), 0, gateSized.error);
        assert.ok(gateSized.error.indexOf("`size` belongs to the square form") >= 0, gateSized.error);
        assert.ok(gateSized.error.indexOf("`margin` to the rectangle form") >= 0, gateSized.error);
        assertNamesTheForms(gateSized.error);
    });
});

test("`margin` with the rectangle it belongs to is the one call that draws ground", function () {
    withGame(function () { /* empty */ }, function () {
        const view = drawn(callTool({ fromX: 15, fromY: 15, toX: 18, toY: 18, margin: 2 }) as MapViewOutcome);

        assert.deepEqual(view.area, { fromX: 13, fromY: 13, toX: 20, toY: 20 },
            "the only form `margin` means anything in, and it means this");
        assert.deepEqual(view.requested, { fromX: 15, fromY: 15, toX: 18, toY: 18 });
    });
});

test("a partial rectangle names what was passed as well as what was missing", function () {
    withGame(function () { /* empty */ }, function () {
        const opposite = callTool({ fromX: 4, toY: 8 }) as ToolFailure;

        assert.equal(opposite.ok, false);
        assert.equal(opposite.error.indexOf("This call passed `fromX`, `toY`."), 0,
            "the two corners it did name: " + opposite.error);
        assert.ok(opposite.error.indexOf("`fromY` and `toX` were left out") >= 0,
            "and the two it did not, read as a sentence: " + opposite.error);
        assertNamesTheForms(opposite.error);

        const three = callTool({ fromX: 4, fromY: 4, toX: 8 }) as ToolFailure;

        assert.equal(three.ok, false);
        assert.equal(three.error.indexOf("This call passed `fromX`, `fromY`, `toX`."), 0, three.error);
        assert.ok(three.error.indexOf("`toY` was left out") >= 0, three.error);

        // A margin on a half-written rectangle: the corner is still what is missing, and the
        // argument that was sent still has to be accounted for rather than passed over.
        const margined = callTool({ fromX: 4, fromY: 4, toX: 8, margin: 3 }) as ToolFailure;

        assert.equal(margined.ok, false);
        assert.equal(margined.error.indexOf("This call passed `fromX`, `fromY`, `toX`, `margin`."), 0,
            margined.error);
        assert.ok(margined.error.indexOf("`toY` was left out") >= 0, margined.error);
        assert.ok(margined.error.indexOf("`margin` is the ground read around those four and does"
            + " not stand in for one of them") >= 0,
            "the call sent `margin`, so the refusal says what it did and did not buy: " + margined.error);
    });
});

test("an x with no y is refused in terms of the whole call, not just the x", function () {
    withGame(function () { /* empty */ }, function () {
        const sized = callTool({ x: 10, size: 7 }) as ToolFailure;

        assert.equal(sized.ok, false);
        assert.equal(sized.error.indexOf("This call passed `x`, `size`."), 0,
            "`size` was passed too, and a refusal saying the call passed `only x` is wrong about"
            + " the call it is refusing: " + sized.error);
        assert.ok(sized.error.indexOf("only `x` of the two") >= 0, sized.error);
        assertNamesTheForms(sized.error);
    });
});

test("an empty call on a park with no gate says it passed nothing, and offers what is left", function () {
    withGame(function () { /* no entrance anywhere */ }, function () {
        const empty = callTool({}) as ToolFailure;

        assert.equal(empty.ok, false);
        assert.equal(empty.error.indexOf("This call passed no arguments at all."), 0,
            "the call named no window, and the refusal says so rather than inventing one: " + empty.error);
        assert.ok(empty.error.indexOf("this park has no gate on the map") >= 0, empty.error);
        assert.ok(empty.error.indexOf("Pass `fromX`, `fromY`, `toX` and `toY` for a rectangle") >= 0,
            empty.error);
        assert.ok(empty.error.indexOf("`x`, `y` and `size` for a square") >= 0, empty.error);

        // The gate-centred square is the form that just failed. Offering it back is the same
        // defect as the `margin` refusal: a shape named to a caller it cannot work for.
        assert.ok(empty.error.indexOf("as a square around the park's own gate") < 0,
            "the gate form cannot be the way out of there being no gate: " + empty.error);

        const sized = callTool({ size: 7 }) as ToolFailure;

        assert.equal(sized.ok, false);
        assert.equal(sized.error.indexOf("This call passed `size`."), 0,
            "`size` selected the gate-centred square, and the refusal names it: " + sized.error);
    });
});

/**
 * Four corners inside the cap, refused by a number the call does not add up to. The margin is
 * the difference and the caller cannot see it from the size alone.
 */
test("a window the margin pushed over the cap says so, and by how much", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ fromX: 5, fromY: 5, toX: 40, toY: 9, margin: 4 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("That window is 44 by 13") >= 0, outcome.error);
        assert.ok(outcome.error.indexOf("The corners named are 36 by 5 tiles and `margin` read 4"
            + " more on every side") >= 0,
            "36 is inside the cap and 44 is not, so the refusal has to name the margin that"
            + " made the difference: " + outcome.error);
        assert.ok(outcome.error.indexOf("a smaller `margin`") >= 0, outcome.error);
    }, 64);
});

test("a rectangle over the cap on its own says nothing about a margin it never had", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ fromX: 5, fromY: 5, toX: 55, toY: 9, margin: 0 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("That window is 51 by 5") >= 0, outcome.error);
        assert.ok(outcome.error.indexOf("`margin`") < 0,
            "the margin was 0 and had nothing to do with it: " + outcome.error);
        assert.ok(outcome.error.indexOf("The corners named") < 0, outcome.error);
    }, 64);
});

test("a rectangle plus its margin can outgrow the cap, and is refused by measurement", function () {
    withGame(function () { /* empty */ }, function () {
        const outcome = callTool({ fromX: 5, fromY: 5, toX: 45, toY: 9, margin: 3 }) as ToolFailure;

        assert.equal(outcome.ok, false);
        assert.ok(outcome.error.indexOf("47 by 11") >= 0,
            "the numbers in the refusal are the size read, margin included: " + outcome.error);
    }, 64);
});

test("size on its own resizes the gate-centred square", function () {
    withGame(function (game) {
        game.addParkEntrance(18, 20);
    }, function () {
        const view = drawn(callTool({ size: 7 }) as MapViewOutcome);

        assert.equal(view.area.toX - view.area.fromX + 1, 7);
        assert.equal(view.area.toY - view.area.fromY + 1, 7);
    });
});

/**
 * The budget, and the honest half of this change.
 *
 * A grid cost one character a tile whatever stood on them. Runs cost by the run, so they are
 * cheaper than the grid on the long stretches a park is mostly made of and dearer on ground
 * that alternates tile by tile - break-even is a run of about three tiles. This fixture is
 * the worse end deliberately: forty single trees scattered through a 15x15 window, which is
 * about two tiles a run, and it is where the encoding costs rather than saves.
 */
test("a busy window of the default size stays inside its budget", function () {
    withGame(function (game) {
        addRide(game, 0);

        for (let x = 12; x <= 15; x++) {
            for (let y = 12; y <= 15; y++) {
                addTrack(game, x, y, 0);
            }
        }

        for (let y = 5; y <= 25; y++) {
            game.addPath(20, y);
        }

        for (let i = 0; i < 40; i++) {
            game.addScenery(10 + (i * 7) % 15, 10 + (i * 11) % 15);
        }
    }, function () {
        const view = drawn(callTool({ x: 17, y: 17 }) as MapViewOutcome);
        const wire = JSON.stringify(view).length;

        assert.ok(wire < 1200, "a " + String(DEFAULT_VIEW_SIZE) + " square came to " + String(wire)
            + " characters; the budget for this is a few hundred tokens");
    });
});

test("a park-sized window of contiguous ground costs less than the grid it replaced", function () {
    // The other end of the same trade, and the one the measured run actually asked for: a
    // 40x40 window whose ground runs in long stretches. The grid was a fixed 2,504 characters
    // on the wire for a window this size whatever was in it.
    withGame(function (game) {
        for (let x = 0; x < 64; x++) {
            for (let y = 0; y < 64; y++) {
                game.own(x, y, x >= 20 && x <= 40 && y >= 20 && y <= 44);
            }
        }

        for (let x = 14; x <= 19; x++) {
            game.addPath(x, 30);
        }

        for (let x = 20; x <= 36; x++) {
            game.addPath(x, 30);
        }

        for (let y = 22; y <= 40; y++) {
            game.addPath(28, y);
        }

        for (let x = 22; x <= 30; x++) {
            for (let y = 34; y <= 40; y++) {
                game.addScenery(x, y);
            }
        }
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 12, right: 47, bottom: 51 }));
        const wire = JSON.stringify(view).length;

        assert.ok(wire < 2504, "a 40x40 window of contiguous ground came to " + String(wire)
            + " characters against the grid's fixed 2,504 for the same window");
        assert.equal(Object.keys(parseRows(view)).length, 1600, "and all 1,600 tiles are still in it");
    }, 64);
});

// ---------------------------------------------------------------------------
// Ownership, which the kind has to carry for paving because paving is the one built thing
// the park lays, replaces and joins onto.
// ---------------------------------------------------------------------------

/**
 * Forest Frontiers, in the shape that cost a run 2,400 pounds.
 *
 * The park's entrance corridor is footpath on land the park neither owns nor can buy, and
 * it runs west out of the park to the gate. Inside the boundary the same line is the park's
 * own trunk walk. Both drew as `P`, so the picture said the park's walk ran eight tiles
 * further west than it does; the model bought land towards a path that was never the
 * park's, said in its own words that a path on non-park land "doesn't make sense", and had
 * nothing in the render it could use to settle it.
 *
 * The owned empty ground beside the corridor is the other half of the lie: `E` next to `P`
 * reads as "pave from here to there", and here there is no there.
 */
function entranceCorridorPark(game: FakeGame): void {
    for (let x = 0; x < 40; x++) {
        for (let y = 0; y < 40; y++) {
            game.own(x, y, x >= 12 && x <= 20 && y >= 8 && y <= 14);
        }
    }

    for (let x = 4; x <= 11; x++) {
        game.addPath(x, 11);          // the corridor: paving, and not the park's
    }

    for (let x = 12; x <= 18; x++) {
        game.addPath(x, 11);          // the trunk: the park's own walk
    }
}

test("a footpath on land the park does not own is a different kind from one on its own", function () {
    withGame(entranceCorridorPark, function () {
        const view = drawn(renderMapView({ left: 4, top: 9, right: 21, bottom: 13 }));

        // The whole corridor in one line, which is the geometry the model got wrong by two
        // columns off the grid and which no counting can get wrong here.
        assert.equal(view.rows[2], "y11: 4-11UP 12-18P 19-20E 21-21U",
            "the boundary between the corridor and the park's own walk falls between 11 and 12,"
            + " and the park's east boundary between 20 and 21");
        assert.equal(kindAt(view, 8, 11), "UP", "the entrance corridor is paving the park does not own");
        assert.equal(kindAt(view, 15, 11), "P", "the trunk inside the boundary is the park's own walk");
        assert.equal(countOf(view, "UP"), 8, "the corridor is x 4 to 11 at y 11 and nothing else");
        assert.equal(countOf(view, "P"), 7, "the trunk is x 12 to 18 at y 11 and nothing else");

        // The configuration that lied: unowned paving with the park's own empty ground
        // beside it. Both facts have to survive into the reading.
        assert.equal(kindAt(view, 12, 10), "E", "the park's ground, flat and empty, beside the corridor's end");
        assert.equal(kindAt(view, 8, 10), "U", "and the ground beside the corridor itself is not the park's");
        assert.equal(kindAt(view, 19, 11), "E", "past the trunk the park's ground is empty again");
    });
});

test("a queue on land the park does not own is a different kind from its own queue", function () {
    withGame(function (game) {
        game.addPath(10, 10, true);
        game.own(12, 10, false);
        game.addPath(12, 10, true);
    }, function () {
        const view = drawn(renderMapView({ left: 8, top: 8, right: 14, bottom: 12 }));

        assert.equal(view.rows[2], "y10: 8-9E 10-10Q 11-11E 12-12UQ 13-14E");
        assert.equal(kindAt(view, 10, 10), "Q", "the park's own queue");
        assert.equal(kindAt(view, 12, 10), "UQ", "a queue on ground the park does not own");
        assert.equal(countOf(view, "Q"), 1, "the unowned queue must not also count as the park's");
        assert.equal(countOf(view, "UQ"), 1);
    });
});
